#!/bin/bash

# compile and rename
lualatex -synctex=1 -interaction=nonstopmode ./master.tex
lualatex -synctex=1 -interaction=nonstopmode ./master.tex
lualatex -synctex=1 -interaction=nonstopmode ./master.tex
cp master.pdf free_range_vhdl.pdf
cp master.synctex.gz free_range_vhdl.synctex.gz
rm master.pdf
rm master.synctex.gz
